language: c++
matrix:
  include:
  - os: linux
    dist: xenial

addons:
  apt:
    packages: texinfo
  homebrew:
    packages: texinfo

git:
  submodules: true

install:
- mkdir -p "${HOME}"/Rack
- pushd "${HOME}"/Rack
- curl -o Rack-SDK.zip https://vcvrack.com/downloads/Rack-SDK-0.6.2.zip
- unzip Rack-SDK.zip
- popd
script:
- export RACK_DIR="${HOME}"/Rack/Rack-SDK
- make deps
- make dist

deploy:
  provider: releases
  api_key:
    secure: RKIjpBO1nmcOFfEZsSubk/KbDwASMLEEX0zv38VjZS6ChvF8mfq14Jim9kw8XXzV3P9jbVF0QWIs9PEYwCjOGEpuykReS5G6x1fsDbw62j8muBW4CS43h+IwQol65x9G46e4xQ7FhXf/9EzUTwejqSF4L08xowA+/2A1sj8UtVhGCl2bgh68ADsRlsUIGABKcyOOLiHOwnt+CydAalixUYje8bqpiEuJYQTrTtDWtH39Ve8dak2mdK2FxrgT2wU0VSSwlNFimGy3snSX95NYyz+H2JglmjxxFczCOZPwN3XGAeoGO+Fy2jhv7OMCxgzrWVwSM6gEImMa4WJHTFnCVNLfBNQ8ZQoDOx5MmE2bK8eah0IK6a0wau9GfGyfRGLN7fX/WNSI7gp2OKjLLusSgLHXHOn7eDqabYol6p3Ea1akmHiLBnwCzG7uLncF9I/p4twEpnqFN2QRqSyIJqT3TlzWdVfZLWL2/1zHDSjCNDHTcIMaDyLLwHtwXGZhDB6gCjDVqNljipnNCAfH8k6CEdelByn7JugrBHk2TljFaYWcSD0Dyp2dsagDOjEykWAgZKwwBR15dgp4jbONvtAwbZU1NlDvqwfhbkEAW3dlEQJ7aTbglDnNrdVJjD1rAmv2wkiIKso5q/EDDFxeADVZ5C3J/duHbmLIrHnjhMbya44=
  file_glob: true
  file: dist/OPL33t-0.6.*-*.zip
  on:
    repo: korfuri/OPL33t
    tags: true
