language: cpp

matrix:
  include:
  - os: linux
    dist: xenial
    # env: BASH="bash -c"
    env: OS_BUILD=lin
  - os: osx
    # env: BASH="bash -c"
    env: OS_BUILD=osx
  - os: windows
    # env: BASH="travis_wait /c/tools/msys64/usr/bin/bash -l -c"
    before_install:
      - choco install cygwin
      - C:\\tools\\cygwin\\cygwinsetup.exe -q -P make,automake,autoconf,libtool
    env: OS_BUILD=win

git:
  submodules: true

install:
- mkdir -p "${HOME}"/Rack
- pushd "${HOME}"/Rack
- curl -o Rack-SDK.zip https://vcvrack.com/downloads/Rack-SDK-0.6.2.zip
- unzip Rack-SDK.zip
- popd

script:
- export RACK_DIR="${HOME}"/Rack/Rack-SDK
- echo Path inside travis.yml $PATH
- if [[ $OS_BUILD == "win" ]]; then
     echo "Building on Windows";
     powershell -Command "C:\tools\cygwin\bin\bash.exe -c './build-windows-travis.sh'";
  else
     make deps;
     make dist;
  fi; exit $?
- ls -laR dist/

deploy:
  provider: releases
  api_key:
    secure: RKIjpBO1nmcOFfEZsSubk/KbDwASMLEEX0zv38VjZS6ChvF8mfq14Jim9kw8XXzV3P9jbVF0QWIs9PEYwCjOGEpuykReS5G6x1fsDbw62j8muBW4CS43h+IwQol65x9G46e4xQ7FhXf/9EzUTwejqSF4L08xowA+/2A1sj8UtVhGCl2bgh68ADsRlsUIGABKcyOOLiHOwnt+CydAalixUYje8bqpiEuJYQTrTtDWtH39Ve8dak2mdK2FxrgT2wU0VSSwlNFimGy3snSX95NYyz+H2JglmjxxFczCOZPwN3XGAeoGO+Fy2jhv7OMCxgzrWVwSM6gEImMa4WJHTFnCVNLfBNQ8ZQoDOx5MmE2bK8eah0IK6a0wau9GfGyfRGLN7fX/WNSI7gp2OKjLLusSgLHXHOn7eDqabYol6p3Ea1akmHiLBnwCzG7uLncF9I/p4twEpnqFN2QRqSyIJqT3TlzWdVfZLWL2/1zHDSjCNDHTcIMaDyLLwHtwXGZhDB6gCjDVqNljipnNCAfH8k6CEdelByn7JugrBHk2TljFaYWcSD0Dyp2dsagDOjEykWAgZKwwBR15dgp4jbONvtAwbZU1NlDvqwfhbkEAW3dlEQJ7aTbglDnNrdVJjD1rAmv2wkiIKso5q/EDDFxeADVZ5C3J/duHbmLIrHnjhMbya44=
  file_glob: true
  file: dist/OPL33t-*-*.zip
  skip_cleanup: true  # Don't remove dist/ before uploading files
  on:
    repo: korfuri/OPL33t
    tags: true
